### PR TITLE
Fix for gun climbing

### PR DESCRIPTION
**Pull request by warbluke**
Harbingers should be less awful to use now. And mortars should stop being as busted too. The comments aren't mine, I just copied them for posterity.

### CODE REVIEW

**Comment by warbluke** [comment]
It turns out Harbingers could not be deployed in this version. Now they can, unless something broke.

**Comment by mattmatterson111** [comment]
If this is a web edit I'm going to end.

**Comment by The-Hotline-System** [comment]
It was a web edit.. i did get him to use applications now, though-


Do not merge.. for now..
I have to look into the ghost trap tiles that get created a lot in warfare by sentries and mortars-

**Comment by warbluke** [comment]
The ghost trap tiles, to my limited understanding, are created when the mortar/mg structure is placed but not deleted. It is normally deleted by reequipping, dropping, or intentionally undeploying the item. It previously could be escaped by climbing out of the tile with the structure, but this has hopefully been fixed. The structure itself prevents tile passage to prevent people using it from dragging it around.
I will redo this via the application over the weekend, I apologize for the inconvenience.

**Comment by mattmatterson111** [comment]
I need you to web update this.

**Comment by warbluke** [comment]
I am closing this so I can make it again without it being a web edit.

**Pull request closed without merging**
